public class pc1 {
    //  practise example for primitive data types
    
    integer i = 10;
    string n = 'nikhil';
    decimal k = 10.05;
    public integer pc1(){
      system.debug('the value of i is ' + i);
        return i ;
    }
public string pc2(){
      system.debug('the value of n is ' + n);
        return n ;
}
     public decimal pc3(){
      system.debug('the value of k is ' + k);
        return k ;
    
}
}