// examples of s object data types

public class pc2 {
    
    account ac = new account ();
       public account pc1(){
        				   ac.Name = 'naidu' ; 
        					ac.Phone = '8552222';
         				  insert ac;
            				 return ac;
                            }
    public static void pc2(){
        course__c cr = new course__c();
        cr.name = 'plsql';
        insert cr;
        
    }

}