// practise class  for extended class
public virtual class pc3 {
    
    integer i = 10;
    string j = 'kumar';
    double d = 15.50;
    
                public  virtual integer pm1(){
                    system.debug('The marks of i was ' + i);
                    return i;
                }
  				  public virtual string pm2(){
                    system.debug('The value of j was ' + j);
                    return j;
                }
    			 public virtual double pm3(){
                    system.debug('The share of kumar was ' + d);
                    return d;
                }

}