public class Swathi_Test {
    
    public static void insertReddy(List<Account> newList){        
        for(Account a : newList){
            a.Name = a.Name + ' Reddy';            
        }        
    }   
    public static void req2(List<Account> newList){
       // Logic         
    }
    public static void req3(List<Account> newList){
                
    }
    public static void req4(List<Account> newList){
                
    }
    public static void req5(List<Account> newList){
                
    }
}